open Ctypes

(* This Types_generated module is an instantiation of the Types
   functor defined in the type_description.ml file. It's generated by
   a C program that Dune creates and runs behind the scenes. *)
module Types = Types_generated

module Functions (F : Ctypes.FOREIGN) = struct
  open F

  let int_id = foreign "int_id" (int @-> returning int)

  let prioritizer =
    foreign
      "prioritizer"
      (ptr int @-> int @-> ptr (ptr int) @-> int @-> returning (ptr int))
  ;;
end
